# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CleanArch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CleanArch

  target 'CleanArchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CleanArchUITests' do
    # Pods for testing
  end

end
